CXXFLAGS = -std=c++11 -O3
#CXXFLAGS = -std=c++11 -g -Wall

all: cipher decipher find bonus

cipher: cipher.cpp pow.h

decipher: decipher.cpp pow.h

find: find.cpp

bonus: bonus.cpp

clean:
	rm cipher decipher find bonus
